version: '3'
services:
  upload:
    image: "node:18"
    command: "npm start"
    volumes: 
      - ./upload:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  gateway:
    image: "node:18"
    command: "npm start"
    volumes: 
      - ./gateway:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "80:80"
    environment:
      POINT_TO: "http://upload:8080"
    depends_on:
      upload:
        condition: service_healthy